### ISSUE TITLE
Docs todo

### ISSUE THREAD

**Issue by jjenzz** [modulz/stitches#66]
From @colmtuite :

- [ ] Components in the code examples should use the primitives, not Radix.
- [ ] Where do I put primitive resets?
- [ ] Get icons working
- [ ] Replace inline styles with component resets
- [ ] Generate title
- [ ] Generate description
- [ ] Give each component a hero, thumbnail and social image.
- [ ] Set component name, description, and social image as og metadata.
- [ ] Add accordion to left sidebar
- [ ] Prevent left sidebar from scrolling to top on page reload.
- [ ] Generate the next/previous links.
- [ ] Generate the scroll spy nav.

**Comment by jjenzz** [comment]
Wrong repo! My bad!
