### ISSUE TITLE
Initial release roadmap 🪂

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#70]
This is the roadmap for the initial release, scheduled for the 31/08/20

### Misc
- [x] Pick a name
- [x] Consider rename `@stitches/css` package to `@stitches/core`
- [x] Consider rename `@stitches/styled` package to `@stitches/react`

### Primary
- [x] Style base 
- [x] Style variants
- [x] Style compound variants (#80)
- [x] Style pseudos
- [x] Style inline medias (#67)
- [x] Nest media queries (#79)
- [x] Style descendant
- [x] Allow `&` at the beginning of a selector (#60)
- [x] Style other Component (#69)
- [x] Create keyframes (#68)
- [x] Allow token-aware values
- [x] Allow negative token-aware values (#78)
- [x] Shorthand property parser #81
- [x] Add a theme
- [x] Add breakpoints
- [x] Compose other Components
- [x] Add `css` prop
- [x] Responsive variant consumption
- [x] Server side rendering
- [x] Convert tokens to CSS variables
- [x] Vendor prefix properties
- [x] Rename "screens" to "mediaQueries" (#84)
- [x] Update the variant syntax (#85)
- [x] Media queries inside variants (#86)

### Secondary
- [x] Multile themes
- [x] Global styles (#65)
- [x] Theme switcher (dark theme)
- [x] Add utils

### Housekeeping
- [ ] Remove tailwind package
- [x] Remove vue package

## Docs
- [x] Build site structure
- [x] Write docs
- [x] New DS built with Stitches

**Comment by colmtuite** [comment]
LGTM, thanks @peduarte.

I'm not sure we need #65 at all? Given that we can do what @jjenzz demoed which includes theme values, and there are perf/bundle benefits that @christianalfoni wanted, it seems like we can omit the feature entirely?

**Comment by peduarte** [comment]
@colmtuite Regarding #65. I have downgraded the priority of that issue, since it can be achieved in a different way. We should still try to implement it at some point though, as it's an expected API for CSS-in-JS.

**Comment by peduarte** [comment]
🚀 We did it!
